const VALID = {
  EMPTY: 1,
  INCLUDE_AT: 2,
  NOT_INCLUDE_AT: 4,
  BELOW_STANDARD: 8,
  EXCEEDING_STANDARD: 16,
  ALREADY_EXIST_EMAIL: 32,
  NOT_EXIST_EMAIL: 64,
  UNAUTHORIZED: 128,
};

export { VALID };
